[2023-06-15T21:24:43.530+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T14:23:04+00:00 [queued]>
[2023-06-15T21:24:43.539+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T14:23:04+00:00 [queued]>
[2023-06-15T21:24:43.539+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T21:24:43.552+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-15 14:23:04+00:00
[2023-06-15T21:24:43.555+0700] {standard_task_runner.py:57} INFO - Started process 80303 to run task
[2023-06-15T21:24:43.562+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-15T14:23:04+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmplo4w_dss']
[2023-06-15T21:24:43.564+0700] {standard_task_runner.py:85} INFO - Job 140: Subtask upload_to_github
[2023-06-15T21:24:43.625+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T14:23:04+00:00 [running]> on host macbook-pro.local
[2023-06-15T21:24:43.696+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T14:23:04+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T14:23:04+00:00'
[2023-06-15T21:24:43.709+0700] {mainflow.py:48} INFO - {'AUTHENTICATION': {'TOKEN': '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', 'USERNAME': 'nxquang-al'}, 'MESSAGE': 'test-github-access-token', 'REPOSITORY': {'BRANCH': 'main', 'NAME': 'Test-github-api', 'OWNER': 'R2th'}}
[2023-06-15T21:24:43.710+0700] {mainflow.py:49} INFO - /Users/lap14202/.airflow/data/Requirements.rst
[2023-06-15T21:24:43.710+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 51, in upload_to_github_task
    upload_to_github(github_config, rst_filepath, log)
TypeError: upload_to_github() takes 2 positional arguments but 3 were given
[2023-06-15T21:24:43.718+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=upload_to_github, execution_date=20230615T142304, start_date=20230615T142443, end_date=20230615T142443
[2023-06-15T21:24:43.726+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 140 for task upload_to_github (upload_to_github() takes 2 positional arguments but 3 were given; 80303)
[2023-06-15T21:24:43.748+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T21:24:43.771+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
