[2023-06-15T19:14:04.567+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.update_index_rst manual__2023-06-15T12:13:35+00:00 [queued]>
[2023-06-15T19:14:04.572+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.update_index_rst manual__2023-06-15T12:13:35+00:00 [queued]>
[2023-06-15T19:14:04.572+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T19:14:04.582+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): update_index_rst> on 2023-06-15 12:13:35+00:00
[2023-06-15T19:14:04.584+0700] {standard_task_runner.py:57} INFO - Started process 60210 to run task
[2023-06-15T19:14:04.589+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'update_index_rst', 'manual__2023-06-15T12:13:35+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmpxwm2mu1v']
[2023-06-15T19:14:04.591+0700] {standard_task_runner.py:85} INFO - Job 67: Subtask update_index_rst
[2023-06-15T19:14:04.633+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.update_index_rst manual__2023-06-15T12:13:35+00:00 [running]> on host macbook-pro.local
[2023-06-15T19:14:04.678+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='update_index_rst' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T12:13:35+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T12:13:35+00:00'
[2023-06-15T19:14:04.687+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 59, in update_index_rst_task
    update_index_rst(github_config, rst_filepath)
TypeError: update_index_rst() takes 0 positional arguments but 2 were given
[2023-06-15T19:14:04.691+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=update_index_rst, execution_date=20230615T121335, start_date=20230615T121404, end_date=20230615T121404
[2023-06-15T19:14:04.697+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 67 for task update_index_rst (update_index_rst() takes 0 positional arguments but 2 were given; 60210)
[2023-06-15T19:14:04.733+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T19:14:04.745+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
