[2023-06-15T01:19:49.693+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TheThree_airflow.load_reqif manual__2023-06-14T18:19:46.074512+00:00 [queued]>
[2023-06-15T01:19:49.699+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TheThree_airflow.load_reqif manual__2023-06-14T18:19:46.074512+00:00 [queued]>
[2023-06-15T01:19:49.699+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T01:19:49.708+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_reqif> on 2023-06-14 18:19:46.074512+00:00
[2023-06-15T01:19:49.710+0700] {standard_task_runner.py:57} INFO - Started process 59173 to run task
[2023-06-15T01:19:49.715+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'TheThree_airflow', 'load_reqif', 'manual__2023-06-14T18:19:46.074512+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmpzn58wj_7']
[2023-06-15T01:19:49.717+0700] {standard_task_runner.py:85} INFO - Job 48: Subtask load_reqif
[2023-06-15T01:19:49.755+0700] {task_command.py:410} INFO - Running <TaskInstance: TheThree_airflow.load_reqif manual__2023-06-14T18:19:46.074512+00:00 [running]> on host macbook-pro.local
[2023-06-15T01:19:49.799+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='TheThree_airflow' AIRFLOW_CTX_TASK_ID='load_reqif' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T18:19:46.074512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T18:19:46.074512+00:00'
[2023-06-15T01:19:49.802+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 12, in load_reqif_task
    reqif = load_reqif(reqif_filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/src/load_reqif.py", line 7, in load_reqif
    return xmltodict.parse(open(filename).read())
                           ^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-06-15T01:19:49.807+0700] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=TheThree_airflow, task_id=load_reqif, execution_date=20230614T181946, start_date=20230614T181949, end_date=20230614T181949
[2023-06-15T01:19:49.814+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task load_reqif (expected str, bytes or os.PathLike object, not NoneType; 59173)
[2023-06-15T01:19:49.857+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T01:19:49.893+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
