[2023-06-15T19:12:32.406+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.build_rst manual__2023-06-15T12:11:14+00:00 [queued]>
[2023-06-15T19:12:32.411+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.build_rst manual__2023-06-15T12:11:14+00:00 [queued]>
[2023-06-15T19:12:32.411+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T19:12:32.423+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): build_rst> on 2023-06-15 12:11:14+00:00
[2023-06-15T19:12:32.426+0700] {standard_task_runner.py:57} INFO - Started process 59937 to run task
[2023-06-15T19:12:32.431+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'build_rst', 'manual__2023-06-15T12:11:14+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmp9zijk9u5']
[2023-06-15T19:12:32.433+0700] {standard_task_runner.py:85} INFO - Job 62: Subtask build_rst
[2023-06-15T19:12:32.474+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.build_rst manual__2023-06-15T12:11:14+00:00 [running]> on host macbook-pro.local
[2023-06-15T19:12:32.522+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='build_rst' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T12:11:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T12:11:14+00:00'
[2023-06-15T19:12:32.531+0700] {mainflow.py:40} INFO - Building rst from {'module': {'name': {'key': 'Module Name', 'value_mapping': {'abc': 'xyx'}}, 'type': {'key': 'Module Type', 'value_mapping': {'type1': 'something need mapping type', 'default_value': 'empty'}}, 'artifacts': {'key': 'List Artifact Info', 'artifact': {'type': {'key': 'Attribute Type', 'value_mapping': {'Heading': 'Heading', 'Information': 'Information', 'MO_FUNC_REQ': 'MO_FUNC_REQ'}, 'default_value': 'xyz'}, 'ReqIF.ForeignID': {'key': 'Identifier', 'value_type': 'number'}, 'ReqIF.ForeignCreatedBy': {'key': 'Creator'}, 'ReqIF.ForeignModifiedBy': {'key': 'Contributor'}, 'ReqIF.ForeignCreatedOn': {'key': 'Created On', 'value_type': 'date'}, 'ReqIF.ForeignModifiedOn': {'key': 'Modified On', 'value_type': 'date'}, 'ReqIF.Text': {'value_type': 'html_string'}, 'ReqIF.Name': {'key': 'Title'}, 'ReqIF.ChapterName': {'key': 'ReqIF.Text', 'value_type': 'html_string'}, 'ReqIF.Description': {'key': 'Description'}, 'Status': {'value_mapping': {'NEW/CHANGED': 'New/Changed'}}, 'Artifact Format': {'ignore': True}, '__rst__': {'heading': {'artifact_type': 'Heading', 'value': 'Title'}, 'information': {'artifact_type': 'Information', 'directives': {'name': 'sw_req', 'attributes': {'id': 'Identifier', 'artifact_type': 'Information'}, 'html_content': 'ReqIF.Text'}}, 'other': {'directives': [{'name': 'sw_req', 'attributes': {'id': 'Identifier', 'artifact_type': 'Description', 'crq': 'crq', 'createdOn': 'Created On'}, 'html_content': 'ReqIF.Text', 'sub_directives': {'verify': 'Verification Criteria', 'safety_level': 'Safety Classification'}}]}}}}}}
[2023-06-15T19:12:32.532+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 42, in build_rst_task
    build_rst(json_data, config, rst_filepath)
  File "/Users/lap14202/.airflow/thethree/build_rst.py", line 95, in build_rst
    rst = RstBuilder(open(filepath, "w"))
                     ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/rst/a.rst'
[2023-06-15T19:12:32.537+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=build_rst, execution_date=20230615T121114, start_date=20230615T121232, end_date=20230615T121232
[2023-06-15T19:12:32.544+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task build_rst ([Errno 2] No such file or directory: '/data/rst/a.rst'; 59937)
[2023-06-15T19:12:32.572+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T19:12:32.599+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
