[2023-06-15T21:06:00.990+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T14:04:46+00:00 [queued]>
[2023-06-15T21:06:00.998+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T14:04:46+00:00 [queued]>
[2023-06-15T21:06:00.999+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T21:06:01.026+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-15 14:04:46+00:00
[2023-06-15T21:06:01.035+0700] {standard_task_runner.py:57} INFO - Started process 77877 to run task
[2023-06-15T21:06:01.043+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-15T14:04:46+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmp6aarsc1q']
[2023-06-15T21:06:01.046+0700] {standard_task_runner.py:85} INFO - Job 128: Subtask upload_to_github
[2023-06-15T21:06:01.172+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T14:04:46+00:00 [running]> on host macbook-pro.local
[2023-06-15T21:06:01.300+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T14:04:46+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T14:04:46+00:00'
[2023-06-15T21:06:01.324+0700] {mainflow.py:48} INFO - {'AUTHENTICATION': {'TOKEN': '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', 'USERNAME': 'nxquang-al'}, 'MESSAGE': 'test-github-access-token', 'REPOSITORY': {'BRANCH': 'main', 'NAME': 'Test-github-api', 'OWNER': 'R2th'}}
[2023-06-15T21:06:01.325+0700] {mainflow.py:49} INFO - /Users/lap14202/.airflow/data/Requirements.rst
[2023-06-15T21:06:01.326+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 51, in upload_to_github_task
    upload_to_github(github_config, rst_filepath, log)
  File "/Users/lap14202/.airflow/thethree/upload_to_github.py", line 82, in upload_to_github
    sha = retrieve_SHA(
          ^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/thethree/upload_to_github.py", line 21, in retrieve_SHA
    response = requests.get(url, headers, data={"branch": branch})
               ^^^^^^^^
NameError: name 'requests' is not defined
[2023-06-15T21:06:01.364+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=upload_to_github, execution_date=20230615T140446, start_date=20230615T140600, end_date=20230615T140601
[2023-06-15T21:06:01.412+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 128 for task upload_to_github (name 'requests' is not defined; 77877)
[2023-06-15T21:06:01.419+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T21:06:01.444+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
