[2023-06-15T14:27:23.636+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.load_reqif manual__2023-06-15T07:26:47+00:00 [queued]>
[2023-06-15T14:27:23.641+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.load_reqif manual__2023-06-15T07:26:47+00:00 [queued]>
[2023-06-15T14:27:23.641+0700] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-06-15T14:27:23.651+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_reqif> on 2023-06-15 07:26:47+00:00
[2023-06-15T14:27:23.653+0700] {standard_task_runner.py:57} INFO - Started process 27587 to run task
[2023-06-15T14:27:23.658+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'load_reqif', 'manual__2023-06-15T07:26:47+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmpgajna739']
[2023-06-15T14:27:23.660+0700] {standard_task_runner.py:85} INFO - Job 47: Subtask load_reqif
[2023-06-15T14:27:23.707+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.load_reqif manual__2023-06-15T07:26:47+00:00 [running]> on host macbook-pro.local
[2023-06-15T14:27:23.756+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='load_reqif' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T07:26:47+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T07:26:47+00:00'
[2023-06-15T14:27:23.758+0700] {mainflow.py:18} INFO - Loading reqif from abc
[2023-06-15T14:27:23.759+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 19, in load_reqif_task
    reqif = load_reqif(reqif_filepath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/thethree/load_reqif.py", line 7, in load_reqif
    return xmltodict.parse(open(filename).read())
                           ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'abc'
[2023-06-15T14:27:23.764+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=load_reqif, execution_date=20230615T072647, start_date=20230615T072723, end_date=20230615T072723
[2023-06-15T14:27:23.771+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task load_reqif ([Errno 2] No such file or directory: 'abc'; 27587)
[2023-06-15T14:27:23.794+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T14:27:23.819+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
