[2023-06-16T13:34:11.202+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.load_reqif_and_configs manual__2023-06-16T06:34:02+00:00 [queued]>
[2023-06-16T13:34:11.208+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.load_reqif_and_configs manual__2023-06-16T06:34:02+00:00 [queued]>
[2023-06-16T13:34:11.208+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-16T13:34:11.223+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_reqif_and_configs> on 2023-06-16 06:34:02+00:00
[2023-06-16T13:34:11.226+0700] {standard_task_runner.py:57} INFO - Started process 10337 to run task
[2023-06-16T13:34:11.233+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'load_reqif_and_configs', 'manual__2023-06-16T06:34:02+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmp6410ylkw']
[2023-06-16T13:34:11.235+0700] {standard_task_runner.py:85} INFO - Job 353: Subtask load_reqif_and_configs
[2023-06-16T13:34:11.298+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.load_reqif_and_configs manual__2023-06-16T06:34:02+00:00 [running]> on host macbook-pro.local
[2023-06-16T13:34:11.389+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='load_reqif_and_configs' AIRFLOW_CTX_EXECUTION_DATE='2023-06-16T06:34:02+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-16T06:34:02+00:00'
[2023-06-16T13:34:11.394+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 18, in load_reqif_and_configs_task
    reqif = load_reqif(reqif_file_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/thethree/load_reqif.py", line 7, in load_reqif
    return xmltodict.parse(open(file_name).read())
                           ^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-06-16T13:34:11.414+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=load_reqif_and_configs, execution_date=20230616T063402, start_date=20230616T063411, end_date=20230616T063411
[2023-06-16T13:34:11.435+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 353 for task load_reqif_and_configs (expected str, bytes or os.PathLike object, not NoneType; 10337)
[2023-06-16T13:34:11.467+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-16T13:34:11.500+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
